name: social_graph
description: "Interactive Graph from scratch in Flutter: Physics, Animations, and CustomPainter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^4.0.1
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  flutter_bloc: ^8.1.3
  uuid: ^4.5.1
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/